config/routes.rb
Ticketee::Application.routes.draw do
  get "users/index"

  devise_for :users
  
  default_url_options :host => "localhost:3000"
  
  resources :projects do
    resources :tickets
  end
  
  root :to => 'projects#index'
  
  namespace :admin do
    root :to => "base#index"
    resources :users
  end
  
  
end

app/models/project.rb
class Project < ActiveRecord::Base
  # Associations
  has_many :tickets
  
  # Validations
  validates :name, :presence => true
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  # Associations
  belongs_to :project
  belongs_to :user
  
  # Validations
  validates :title, :presence => true
  validates :description, :presence => true, :length => {:minimum => 10}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  def to_s
    "#{email} (#{admin? ? "Admin" : "User"})"
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :authorize_admin!
  
  def index
    
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def index
    @users = User.all(:order => "email")
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    @user.admin = params[:user][:admin] == "1"
    if @user.save
      flash[:notice] = "User has been created."
      redirect_to admin_users_path
    else
      flash[:alert] = "User has not been created."
      render :action => "new"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :mailer_set_url_options
  
  def mailer_set_url_options
    ActionMailer::Base.default_url_options[:host] = request.host_with_port
  end
  
  private
  
  def authorize_admin!
    authenticate_user!
    unless current_user.admin?
      flash[:alert] = "You must be an admin to do that."
      redirect_to root_path
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # Filters
  before_filter :authorize_admin!, :except => [:index, :show]
  before_filter :find_project, :only => [:show, :update, :edit, :destroy]
  
  # Actions
  def index
    @projects = Project.all
  end
  
  def new
    @project = Project.new
  end
  
  def show
    @project = Project.find(params[:id])
  end
  
  def create
    @project = Project.new(params[:project])
    if @project.save
      flash[:notice] = "Project has been created."
      redirect_to @project
    else
      flash[:alert] = "Project has not been created."
      render :action => "new"
    end
  end
  
  def edit
    @project = Project.find(params[:id])
  end
  
  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      flash[:notice] = "Project has been updated."
      redirect_to @project
    else
      flash[:alert] = "Project has not been updated."
      render :action => "edit"
    end
  end
  
  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    flash[:notice] = "Project has been deleted."
    redirect_to projects_path
  end
  
  private
  
  def authorize_admin!
    authenticate_user!
    unless current_user.admin?
      flash[:alert] = "You must be an admin to do that."
      redirect_to root_path
    end
  end
  
  def find_project
    @project = Project.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The project you were looking for could not be found."
    redirect_to projects_path 
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  # Filters
  before_filter :authenticate_user!, :except => [:index, :show]
  before_filter :find_project
  before_filter :find_ticket, :only => [:show, :edit, :update, :destroy]
  
  # Actions
  def new
    @ticket = @project.tickets.build
  end
  
  def show
  end
  
  def edit
  end
  
  def create
    @ticket = @project.tickets.build(params[:ticket].merge!(:user => current_user))
    if @ticket.save
      flash[:notice] = "Ticket has been created."
      redirect_to [@project, @ticket]
    else
      flash[:alert] = "Ticket has not been created."
      render :action => "new"
    end
  end
  
  def update
    if @ticket.update_attributes(params[:ticket])
      flash[:notice] = "Ticket has been updated."
      redirect_to [@project, @ticket]
    else
      flash[:alert] = "Ticket has not been updated."
      render :action => "edit"
    end
  end
  
  def destroy
    @ticket.destroy
    flash[:notice] = "Ticket has been deleted."
    redirect_to @project
  end
  
  private
  
  def find_project
    @project = Project.find(params[:project_id])
  end
  
  def find_ticket
    @ticket = @project.tickets.find(params[:id])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << "Ticketee").join(" - ") unless parts.empty?
      end
    end
  end
  
  def admins_only(&block)
    block.call if current_user.try(:admin?)
    nil
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/admin/base/index.html.erb
<%= link_to "Users", admin_users_path %>
Welcome to Ticketee's Admin Lounge. Please enjoy your stay.

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
<%= f.error_messages %>
<p>
  <%= f.label :email %>
  <%= f.text_field :email %>
</p>
<p>
  <%= f.label :password %>
  <%= f.password_field :password %>
</p>
<p>
  <%= f.check_box :admin %>
  <%= f.label :admin, "Is an admin?" %>
</p>
<%= f.submit %>
<% end %>

app/views/admin/users/index.html.erb
<%= link_to "New User", new_admin_user_path %>
<ul>
	<% @users.each do |user| %>
		<li><%= link_to user, [:admin, user ]%></li>
	<% end %>
</ul>

app/views/admin/users/new.html.erb
<h2>New User</h2>
<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <% if content_for?(:title) %>
      <%= yield(:title) %>
    <% else %>
      Ticketee
    <% end %>
  </title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |key, value| %>
  <div class='flash' id='<%= key %>'>
    <%= value %>
  </div>
<% end %>
<h1><%= link_to "Ticketee", root_path %></h1>
<nav>
	<% if user_signed_in? %>
		Signed in as <%= current_user.email%>
		<%= admins_only do %>
			<%= link_to "Admin", admin_root_path %><br />
		<% end %>
	<% else %>
		<%= link_to "Sign up", new_user_registration_path %> or
		<%= link_to "Sign in", new_user_session_path %>
	<% end %>
</nav>
<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
<%= f.error_messages %>
	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>
	<%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h2>Edit project</h2>
<%= render "form" %>

app/views/projects/index.html.erb
<%= admins_only do %>
	<%= link_to "New Project", new_project_path %>
<% end %>
<h2>Projects</h2>
<ul>
	<% @projects.each do |project| %>
		<li><%= link_to project.name, project %></li>
	<% end %>
</ul>

app/views/projects/new.html.erb
<%= render 'form' %>

app/views/projects/show.html.erb
<% title(@project.name,"Projects") %>
<%= admins_only do %>
	<%= link_to "Edit Project", edit_project_path(@project) %>
	<%= link_to "Delete Project", @project, :method => :delete, :confirm => "Are you sure you want to delete this project?" %>
<% end %>
<%= link_to "New Ticket", new_project_ticket_path(@project) %>
<ul id='tickets'>
	<% @project.tickets.each do |ticket| %>
		<li>
			#<%= ticket.id %> - <%= link_to ticket.title, [@project, ticket] %>
		</li>
	<% end %>
</ul>

app/views/tickets/_form.html.erb
<%= form_for [@project, @ticket] do |f| %>
	<%= f.error_messages %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :description %>
		<%= f.text_area :description %>
	</p>
	<%= f.submit %>
<% end %>

app/views/tickets/edit.html.erb
<h2>Editing a ticket in <%= @project.name %></h2>
<%= render "form" %>

app/views/tickets/new.html.erb
<h2>New Ticket</h2>
<%= render "form" %>

app/views/tickets/show.html.erb
<div id='ticket'>
	<h2><%= @ticket.title %></h2>
	<br><small>Created by <%= @ticket.user.email %></small>
	<%= simple_format(@ticket.description) %>
</div>
<%= link_to "Edit Ticket", [:edit, @project, @ticket] %>
<%= link_to "Delete Ticket", [@project, @ticket], :method => :delete, :confirm => "Are you sure you want to delete this ticket?" %>